project_id = "yiitqkjrbskxumriujrh"

[functions.getstream-token]
verify_jwt = false

[functions.broadcasts-create]
verify_jwt = true

[functions.broadcasts-react]
verify_jwt = true

[functions.broadcasts-fetch]
verify_jwt = true

[functions.file-upload]
verify_jwt = true

[functions.photo-upload]
verify_jwt = true

[functions.receipt-parser]
verify_jwt = true

[functions.calendar-sync]
verify_jwt = true

[functions.venue-enricher]
verify_jwt = true

[functions.file-ai-parser]
verify_jwt = true

[functions.search]
verify_jwt = false

[functions.populate-search-index]
verify_jwt = false

[functions.create-invite]
verify_jwt = true
